server:
  port: 9999
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eason-ops/aispringcloud.git
          searchPaths: config
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1234/eureka/
