server:
  port: 9999
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eason-ops/aispringcloud.git
          searchPaths: config
          username: Eason-ops
          password: Aiwodeni19910113
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
